# creating np arrays

In [2]:
import numpy as np

In [4]:
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
zeroarray = np.zeros(8)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
ones = np.ones(4)
print(ones)

[1. 1. 1. 1.]


In [42]:
empty = np.empty(1)
print(empty)

[0.]


In [3]:
# arange

table2 = np.arange(2, 21, 2)
table3 = np.arange(3, 31, 3)
table25 = np.arange(25, 251, 25)
range  = np.arange(10000)

print(table2)
print(table3)
print(table25)
print(range)

[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 25  50  75 100 125 150 175 200 225 250]
[   0    1    2 ... 9997 9998 9999]


In [5]:
# linespace
ls = np.linspace(1,2, dtype=np.float16)
print(ls)

[1.     1.0205 1.041  1.062  1.082  1.102  1.122  1.143  1.163  1.184
 1.204  1.225  1.245  1.266  1.286  1.306  1.326  1.347  1.367  1.388
 1.408  1.429  1.449  1.47   1.49   1.51   1.53   1.551  1.571  1.592
 1.612  1.633  1.653  1.674  1.694  1.714  1.734  1.755  1.775  1.796
 1.816  1.837  1.857  1.878  1.898  1.918  1.938  1.959  1.9795 2.    ]
